### ISSUE TITLE
Unstarted items imported into Estimator from Backlog should be made started

### ISSUE THREAD

**Issue by spfrommer** [ScientificRevenue/backlogger#10]

**Comment by rliebling** [comment]
not sure they need to be made started.  they need to be in the current/backlog (not icebox) to indicate that they don't need to be estimated.  But, started vs nonstarted i don't think matters.  I may be missing something.  But, in particular, when they go back to Backlog if they were not started in backlog should not be started after the estimation round-trip.

**Comment by spfrommer** [comment]
Issue arises because pivotal separates unstarted and started stories, even if they are both in the pivotal backlog. Stories would look like:
Started
Started
Started
...
Unstarted
Unstarted
...
Which creates obvious problems when trying to assign effort order and point estimates, since pivotal doesn't allow you to mix these even with manual rearrangement. My idea is just to make all stories "started" in the Estimator backlog and then change them back to their original states when finishing the round-trip (I have already finished this). This would mean that if you change the state of the story in Estimator it would unfortunately be reverted when the estimation session is finished, but I unfortunately don't see a way around this...

**Comment by rliebling** [comment]
got it.  thx
